
module.exports = {
  "js/no-atom.config.unobserve": "error",
  "js/no-require-view": "error",
  "js/no-require-editorView": "error",
  "js/no-require-scrollView": "error",
  "js/no-require-selectListView": "error",
  "js/no-require-textEditorView": "error",
  "js/no-require-dollarSign": "error",
  "js/no-require-doubleDollarSign": "error",
  "js/no-require-tripleDollarSign": "error",
  "js/no-atom.services": "error",
  "js/no-atom.workspaceView": "error",
  "js/no-atom.syntax": "error",
  "js/no-atom.registerRepresentationClass": "error",
  "js/no-atom.registerRepresentationClasses": "error",
  "js/rename-atom.workspace-changeFocus": "error",
  "js/no-atom.showSaveDialogSync": "warn",
  "js/no-promise.done": "warn",
  "js/no-dock.getActiveTextEditor": "warn",
  "js/useString-path.dirname": "warn",
  "js/no-atom.workspace.paneContainer": "warn",
  "js/modify-atom.views.addViewProvider-argumentsLength": "warn",
  "js/useString-path.extname": "warn",
  "js/useStrings-path.basename": "warn",
  "js/no-electron.ipcRenderer.sendChannel": "warn",
  "js/no-electron.remote.require-Module": "warn",
  "js/no-require.deprecatedModules": "warn",
};
